version: '3.9'
services:
  node1:
    build: .
    container_name: node1
    networks:
      - consensus_network
    environment:
      - NODE_ID=1
      - PEERS=2,3
    ports:
      - "5001:5001"

  node2:
    build: .
    container_name: node2
    networks:
      - consensus_network
    environment:
      - NODE_ID=2
      - PEERS=1,3
    ports:
      - "5002:5002"

  node3:
    build: .
    container_name: node3
    networks:
      - consensus_network
    environment:
      - NODE_ID=3
      - PEERS=1,2
    ports:
      - "5003:5003"

networks:
  consensus_network:
    driver: bridge
